### ISSUE TITLE
SelectField Undefined

### ISSUE THREAD

**Issue by wang3620** [zdmi/redux-form-antd#47]
Hello,

Here is the screenshot from my google debugger. I am not sure why my SelectField is undefined here. I am pretty sure I have installed "redux-form-antd": "3.1.4"

![screen shot 2018-12-11 at 6 23 33 pm](https://user-images.githubusercontent.com/22897208/49842930-37db0600-fd72-11e8-9a2a-e4ff3acaebe5.png)

**Comment by zhDmitry** [comment]
try to install previous version, the new version is just code refactoring no big changes
