### ISSUE TITLE
Bug with method binding in 3.1.4 v

### ISSUE THREAD

**Issue by bogdaniy** [zdmi/redux-form-antd#48]
In constructor of Component `src/components/BaseComponent` you have line `this.initComponentRef.bind(this)` but bind creates a new function, instead of mutating old. So all components don't work in the last version. I was confused when tried to integrate it into a project.

**Comment by greyivy** [comment]
Also ran into this issue.

**Comment by zhDmitry** [comment]
try to install previous version, the new version is just code refactoring no big changes
